### ISSUE TITLE
error in plot handling.

### ISSUE THREAD

**Issue by edvinf** [StoXProject/RstoxFramework#287]
With the pre-relase 3.6.3-9006, I get the following error when trying to produce plots:
"object is not coercible to a unit".

The traceback seem to indicate this happens when RstoxFramework applies getPrecisionDigits to functions that return ggplot-objects.

Excerpt from traceback:
20: as.unit(e1)
19: Ops.unit(signifDigits, floor(log10(abs(x))))
18: pmax(signifDigits - floor(log10(abs(x))) - 1, digits)
17: getPrecisionDigits(x, digits = digits, signifDigits = signifDigits)
16: roundSignif(x, digits = digits, signifDigits = signifDigits)
15: FUN(X[[i]], ...)
14: lapply(x, setRstoxPrecision)

**Comment by arnejohannesholmin** [comment]
This was fixed in StoX 4.0.0.
